matrix:
  VERSION:
    - "0.5.0"

clone:
  path: github.com/jwilder

build:
  image: armhfbuild/golang:1.5
  commands:
    - git clone --single-branch --branch $$VERSION https://github.com/jwilder/docker-gen
    - cd docker-gen
    - make get-deps docker-gen test
    - sed -i 's/FROM debian/FROM armhfbuild\/debian/' Dockerfile
    - sed -i 's/amd64/armhf/' Dockerfile

publish:
  docker:
    image: armhfplugins/drone-docker:docker-caching
    context: docker-gen
    file: docker-gen/Dockerfile
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: armhfbuild/docker-gen
    tag: $$VERSION

cache:
  mount:
    - /drone/docker
