matrix:
  VERSION:
    - master
    - "0.7.3"

pipeline:
  clone:
    image: armhfplugins/git

  build:
    image: armhfbuild/golang:1.5
    commands:
      - git clone --single-branch --branch ${VERSION} https://github.com/jwilder/docker-gen
      - cd docker-gen
      - sed -i 's/FROM alpine/FROM armhfbuild\/alpine/' Dockerfile
      - sed -i 's/alpine-linux-amd64/linux-armhf/' Dockerfile

  publish_docker_branch:
    image: armhfplugins/docker
    context: docker-gen
    dockerfile: docker-gen/Dockerfile
    username: ${DOCKER_USER}
    password: ${DOCKER_PASSWORD}
    email: ${DOCKER_EMAIL}
    repo: armhfbuild/docker-gen
    tags: [ "0.7.3", "0.7", "latest" ]
    when:
      matrix:
        VERSION: "0.7.3"

  publish_docker_latest:
    image: armhfplugins/docker
    context: docker-gen
    dockerfile: docker-gen/Dockerfile
    username: ${DOCKER_USER}
    password: ${DOCKER_PASSWORD}
    email: ${DOCKER_EMAIL}
    repo: armhfbuild/docker-gen
    tags: [ "master" ]
    when:
      matrix:
        VERSION: master
