matrix:
  VERSION:
    - master
    - "0.5.0"

workspace:
  base: /go
  path: src/github.com/jwilder

pipeline:
  clone:
    image: armhfplugins/git
    path: github.com/jwilder

  build:
    image: armhfbuild/golang:1.5
    commands:
      - git clone --single-branch --branch ${VERSION} https://github.com/jwilder/docker-gen
      - cd docker-gen
      - make get-deps docker-gen test
      - sed -i 's/FROM debian/FROM armhfbuild\/debian/' Dockerfile
      - sed -i 's/amd64/armhf/' Dockerfile

  publish_docker_branch:
    image: armhfplugins/docker
    context: docker-gen
    dockerfile: docker-gen/Dockerfile
    username: ${DOCKER_USER}
    password: ${DOCKER_PASSWORD}
    email: ${DOCKER_EMAIL}
    repo: armhfbuild/docker-gen
    tags: [ "${VERSION}" ]

  publish_docker_latest:
    image: armhfplugins/docker
    context: docker-gen
    dockerfile: docker-gen/Dockerfile
    username: ${DOCKER_USER}
    password: ${DOCKER_PASSWORD}
    email: ${DOCKER_EMAIL}
    repo: armhfbuild/docker-gen
    tag: latest
    when:
      matrix:
        VERSION: master
